apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapi-deployment
  labels:
    app: dotnet-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-webapi
  template:
    metadata:
      labels:
        app: dotnet-webapi
    spec:
      containers:
        - name: dotnet-webapi
          image: dockerimage.azurecr.io/terra-jenk-docker:latest 
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-webapi-service
spec:
  type: LoadBalancer
  selector:
    app: dotnet-webapi
  ports:
    - port: 80
      targetPort: 8080
